# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='autor_name',
            new_name='author_name',
        ),
    ]
